"""Generate structural node types and positional factories from CPython ASDL."""

import io

BUILTINS = {"identifier": "string", "string": "string", "int": "number", "constant": "ScalarConstant"}


def identifier(name):
    return "arguments_" if name == "arguments" else name


def field_type(field):
    result = BUILTINS.get(field.type, identifier(field.type))
    # Since 3.14, ordered quantifiers distinguish expr?* from expr*?.
    # Field.opt/seq describe only the final quantifier and lose nullable elements.
    import asdl

    for quantifier in field.quantifiers:
        if quantifier is asdl.Quantifier.OPTIONAL:
            result += " | null"
        elif quantifier is asdl.Quantifier.SEQUENCE:
            result = f"({result})[]" if " | " in result else result + "[]"
        else:
            raise ValueError(f"Unsupported ASDL quantifier: {quantifier}")
    return result


def generate(schema, lock):
    import asdl

    out = io.StringIO()

    def emit(line=""):
        out.write(line + "\n")

    emit("// Copyright (c) 2021 the Skulpt Project")
    emit("// SPDX-License-Identifier: MIT")
    emit("// Generated by python -m tools.generate314; do not edit.")
    emit(f'// CPython {lock["version"]}, commit {lock["commit"]}; Parser/Python.asdl.')
    emit("// Upstream schema license: licenses/CPython.txt.")
    emit('import type { ScalarConstant } from "./constants.ts";')
    emit()
    roots = []
    for definition in schema.dfns:
        value = definition.value
        name = identifier(definition.name)
        roots.append(name)
        if isinstance(value, asdl.Sum):
            emit(f"export type {name} = " + " | ".join(node.name for node in value.types) + ";")
        nodes = value.types if isinstance(value, asdl.Sum) else [value]
        for node in nodes:
            tag = node.name if isinstance(value, asdl.Sum) else definition.name
            name = identifier(tag)
            fields = [*node.fields, *value.attributes]
            emit(f"export interface {name} {{")
            emit(f'    _type: "{tag}";')
            for field in fields:
                emit(f"    {field.name}: {field_type(field)};")
            emit("}")
            emit(f"export function {name}(")
            for field in fields:
                emit(f"    {field.name}: {field_type(field)},")
            emit(f"): {name} {{")
            properties = ", ".join(field.name for field in fields)
            emit(f'    return {{ _type: "{tag}"' + (", " + properties if properties else "") + " };")
            emit("}")
            if tag != name:
                emit(f"export {{ {name} as {tag} }};")
            emit()
    emit("export type AST = " + " | ".join(roots) + ";")
    return out.getvalue()
