// Copyright (c) 2021 the Skulpt Project
// SPDX-License-Identifier: MIT
// Generated by python -m tools.generate314; do not edit.
// CPython 3.14.3, commit 323c59a5e348347be2ce2b7ea55fcb30bf68b2d3; Parser/Python.asdl.
// Upstream schema license: licenses/CPython.txt.
import type { ScalarConstant } from "./constants.ts";

export type mod = Module | Interactive | Expression | FunctionType;
export interface Module {
    _type: "Module";
    body: stmt[];
    type_ignores: type_ignore[];
}
export function Module(
    body: stmt[],
    type_ignores: type_ignore[],
): Module {
    return { _type: "Module", body, type_ignores };
}

export interface Interactive {
    _type: "Interactive";
    body: stmt[];
}
export function Interactive(
    body: stmt[],
): Interactive {
    return { _type: "Interactive", body };
}

export interface Expression {
    _type: "Expression";
    body: expr;
}
export function Expression(
    body: expr,
): Expression {
    return { _type: "Expression", body };
}

export interface FunctionType {
    _type: "FunctionType";
    argtypes: expr[];
    returns: expr;
}
export function FunctionType(
    argtypes: expr[],
    returns: expr,
): FunctionType {
    return { _type: "FunctionType", argtypes, returns };
}

export type stmt = FunctionDef | AsyncFunctionDef | ClassDef | Return | Delete | Assign | TypeAlias | AugAssign | AnnAssign | For | AsyncFor | While | If | With | AsyncWith | Match | Raise | Try | TryStar | Assert | Import | ImportFrom | Global | Nonlocal | Expr | Pass | Break | Continue;
export interface FunctionDef {
    _type: "FunctionDef";
    name: string;
    args: arguments_;
    body: stmt[];
    decorator_list: expr[];
    returns: expr | null;
    type_comment: string | null;
    type_params: type_param[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function FunctionDef(
    name: string,
    args: arguments_,
    body: stmt[],
    decorator_list: expr[],
    returns: expr | null,
    type_comment: string | null,
    type_params: type_param[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): FunctionDef {
    return { _type: "FunctionDef", name, args, body, decorator_list, returns, type_comment, type_params, lineno, col_offset, end_lineno, end_col_offset };
}

export interface AsyncFunctionDef {
    _type: "AsyncFunctionDef";
    name: string;
    args: arguments_;
    body: stmt[];
    decorator_list: expr[];
    returns: expr | null;
    type_comment: string | null;
    type_params: type_param[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function AsyncFunctionDef(
    name: string,
    args: arguments_,
    body: stmt[],
    decorator_list: expr[],
    returns: expr | null,
    type_comment: string | null,
    type_params: type_param[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): AsyncFunctionDef {
    return { _type: "AsyncFunctionDef", name, args, body, decorator_list, returns, type_comment, type_params, lineno, col_offset, end_lineno, end_col_offset };
}

export interface ClassDef {
    _type: "ClassDef";
    name: string;
    bases: expr[];
    keywords: keyword[];
    body: stmt[];
    decorator_list: expr[];
    type_params: type_param[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function ClassDef(
    name: string,
    bases: expr[],
    keywords: keyword[],
    body: stmt[],
    decorator_list: expr[],
    type_params: type_param[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): ClassDef {
    return { _type: "ClassDef", name, bases, keywords, body, decorator_list, type_params, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Return {
    _type: "Return";
    value: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Return(
    value: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Return {
    return { _type: "Return", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Delete {
    _type: "Delete";
    targets: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Delete(
    targets: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Delete {
    return { _type: "Delete", targets, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Assign {
    _type: "Assign";
    targets: expr[];
    value: expr;
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Assign(
    targets: expr[],
    value: expr,
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Assign {
    return { _type: "Assign", targets, value, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface TypeAlias {
    _type: "TypeAlias";
    name: expr;
    type_params: type_param[];
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function TypeAlias(
    name: expr,
    type_params: type_param[],
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): TypeAlias {
    return { _type: "TypeAlias", name, type_params, value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface AugAssign {
    _type: "AugAssign";
    target: expr;
    op: operator;
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function AugAssign(
    target: expr,
    op: operator,
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): AugAssign {
    return { _type: "AugAssign", target, op, value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface AnnAssign {
    _type: "AnnAssign";
    target: expr;
    annotation: expr;
    value: expr | null;
    simple: number;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function AnnAssign(
    target: expr,
    annotation: expr,
    value: expr | null,
    simple: number,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): AnnAssign {
    return { _type: "AnnAssign", target, annotation, value, simple, lineno, col_offset, end_lineno, end_col_offset };
}

export interface For {
    _type: "For";
    target: expr;
    iter: expr;
    body: stmt[];
    orelse: stmt[];
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function For(
    target: expr,
    iter: expr,
    body: stmt[],
    orelse: stmt[],
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): For {
    return { _type: "For", target, iter, body, orelse, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface AsyncFor {
    _type: "AsyncFor";
    target: expr;
    iter: expr;
    body: stmt[];
    orelse: stmt[];
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function AsyncFor(
    target: expr,
    iter: expr,
    body: stmt[],
    orelse: stmt[],
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): AsyncFor {
    return { _type: "AsyncFor", target, iter, body, orelse, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface While {
    _type: "While";
    test: expr;
    body: stmt[];
    orelse: stmt[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function While(
    test: expr,
    body: stmt[],
    orelse: stmt[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): While {
    return { _type: "While", test, body, orelse, lineno, col_offset, end_lineno, end_col_offset };
}

export interface If {
    _type: "If";
    test: expr;
    body: stmt[];
    orelse: stmt[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function If(
    test: expr,
    body: stmt[],
    orelse: stmt[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): If {
    return { _type: "If", test, body, orelse, lineno, col_offset, end_lineno, end_col_offset };
}

export interface With {
    _type: "With";
    items: withitem[];
    body: stmt[];
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function With(
    items: withitem[],
    body: stmt[],
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): With {
    return { _type: "With", items, body, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface AsyncWith {
    _type: "AsyncWith";
    items: withitem[];
    body: stmt[];
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function AsyncWith(
    items: withitem[],
    body: stmt[],
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): AsyncWith {
    return { _type: "AsyncWith", items, body, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Match {
    _type: "Match";
    subject: expr;
    cases: match_case[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Match(
    subject: expr,
    cases: match_case[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Match {
    return { _type: "Match", subject, cases, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Raise {
    _type: "Raise";
    exc: expr | null;
    cause: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Raise(
    exc: expr | null,
    cause: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Raise {
    return { _type: "Raise", exc, cause, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Try {
    _type: "Try";
    body: stmt[];
    handlers: excepthandler[];
    orelse: stmt[];
    finalbody: stmt[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Try(
    body: stmt[],
    handlers: excepthandler[],
    orelse: stmt[],
    finalbody: stmt[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Try {
    return { _type: "Try", body, handlers, orelse, finalbody, lineno, col_offset, end_lineno, end_col_offset };
}

export interface TryStar {
    _type: "TryStar";
    body: stmt[];
    handlers: excepthandler[];
    orelse: stmt[];
    finalbody: stmt[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function TryStar(
    body: stmt[],
    handlers: excepthandler[],
    orelse: stmt[],
    finalbody: stmt[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): TryStar {
    return { _type: "TryStar", body, handlers, orelse, finalbody, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Assert {
    _type: "Assert";
    test: expr;
    msg: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Assert(
    test: expr,
    msg: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Assert {
    return { _type: "Assert", test, msg, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Import {
    _type: "Import";
    names: alias[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Import(
    names: alias[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Import {
    return { _type: "Import", names, lineno, col_offset, end_lineno, end_col_offset };
}

export interface ImportFrom {
    _type: "ImportFrom";
    module: string | null;
    names: alias[];
    level: number | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function ImportFrom(
    module: string | null,
    names: alias[],
    level: number | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): ImportFrom {
    return { _type: "ImportFrom", module, names, level, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Global {
    _type: "Global";
    names: string[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Global(
    names: string[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Global {
    return { _type: "Global", names, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Nonlocal {
    _type: "Nonlocal";
    names: string[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Nonlocal(
    names: string[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Nonlocal {
    return { _type: "Nonlocal", names, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Expr {
    _type: "Expr";
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Expr(
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Expr {
    return { _type: "Expr", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Pass {
    _type: "Pass";
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Pass(
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Pass {
    return { _type: "Pass", lineno, col_offset, end_lineno, end_col_offset };
}

export interface Break {
    _type: "Break";
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Break(
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Break {
    return { _type: "Break", lineno, col_offset, end_lineno, end_col_offset };
}

export interface Continue {
    _type: "Continue";
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Continue(
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Continue {
    return { _type: "Continue", lineno, col_offset, end_lineno, end_col_offset };
}

export type expr = BoolOp | NamedExpr | BinOp | UnaryOp | Lambda | IfExp | Dict | Set | ListComp | SetComp | DictComp | GeneratorExp | Await | Yield | YieldFrom | Compare | Call | FormattedValue | Interpolation | JoinedStr | TemplateStr | Constant | Attribute | Subscript | Starred | Name | List | Tuple | Slice;
export interface BoolOp {
    _type: "BoolOp";
    op: boolop;
    values: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function BoolOp(
    op: boolop,
    values: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): BoolOp {
    return { _type: "BoolOp", op, values, lineno, col_offset, end_lineno, end_col_offset };
}

export interface NamedExpr {
    _type: "NamedExpr";
    target: expr;
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function NamedExpr(
    target: expr,
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): NamedExpr {
    return { _type: "NamedExpr", target, value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface BinOp {
    _type: "BinOp";
    left: expr;
    op: operator;
    right: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function BinOp(
    left: expr,
    op: operator,
    right: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): BinOp {
    return { _type: "BinOp", left, op, right, lineno, col_offset, end_lineno, end_col_offset };
}

export interface UnaryOp {
    _type: "UnaryOp";
    op: unaryop;
    operand: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function UnaryOp(
    op: unaryop,
    operand: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): UnaryOp {
    return { _type: "UnaryOp", op, operand, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Lambda {
    _type: "Lambda";
    args: arguments_;
    body: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Lambda(
    args: arguments_,
    body: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Lambda {
    return { _type: "Lambda", args, body, lineno, col_offset, end_lineno, end_col_offset };
}

export interface IfExp {
    _type: "IfExp";
    test: expr;
    body: expr;
    orelse: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function IfExp(
    test: expr,
    body: expr,
    orelse: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): IfExp {
    return { _type: "IfExp", test, body, orelse, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Dict {
    _type: "Dict";
    keys: (expr | null)[];
    values: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Dict(
    keys: (expr | null)[],
    values: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Dict {
    return { _type: "Dict", keys, values, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Set {
    _type: "Set";
    elts: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Set(
    elts: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Set {
    return { _type: "Set", elts, lineno, col_offset, end_lineno, end_col_offset };
}

export interface ListComp {
    _type: "ListComp";
    elt: expr;
    generators: comprehension[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function ListComp(
    elt: expr,
    generators: comprehension[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): ListComp {
    return { _type: "ListComp", elt, generators, lineno, col_offset, end_lineno, end_col_offset };
}

export interface SetComp {
    _type: "SetComp";
    elt: expr;
    generators: comprehension[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function SetComp(
    elt: expr,
    generators: comprehension[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): SetComp {
    return { _type: "SetComp", elt, generators, lineno, col_offset, end_lineno, end_col_offset };
}

export interface DictComp {
    _type: "DictComp";
    key: expr;
    value: expr;
    generators: comprehension[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function DictComp(
    key: expr,
    value: expr,
    generators: comprehension[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): DictComp {
    return { _type: "DictComp", key, value, generators, lineno, col_offset, end_lineno, end_col_offset };
}

export interface GeneratorExp {
    _type: "GeneratorExp";
    elt: expr;
    generators: comprehension[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function GeneratorExp(
    elt: expr,
    generators: comprehension[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): GeneratorExp {
    return { _type: "GeneratorExp", elt, generators, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Await {
    _type: "Await";
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Await(
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Await {
    return { _type: "Await", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Yield {
    _type: "Yield";
    value: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Yield(
    value: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Yield {
    return { _type: "Yield", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface YieldFrom {
    _type: "YieldFrom";
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function YieldFrom(
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): YieldFrom {
    return { _type: "YieldFrom", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Compare {
    _type: "Compare";
    left: expr;
    ops: cmpop[];
    comparators: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Compare(
    left: expr,
    ops: cmpop[],
    comparators: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Compare {
    return { _type: "Compare", left, ops, comparators, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Call {
    _type: "Call";
    func: expr;
    args: expr[];
    keywords: keyword[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Call(
    func: expr,
    args: expr[],
    keywords: keyword[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Call {
    return { _type: "Call", func, args, keywords, lineno, col_offset, end_lineno, end_col_offset };
}

export interface FormattedValue {
    _type: "FormattedValue";
    value: expr;
    conversion: number;
    format_spec: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function FormattedValue(
    value: expr,
    conversion: number,
    format_spec: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): FormattedValue {
    return { _type: "FormattedValue", value, conversion, format_spec, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Interpolation {
    _type: "Interpolation";
    value: expr;
    str: ScalarConstant;
    conversion: number;
    format_spec: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Interpolation(
    value: expr,
    str: ScalarConstant,
    conversion: number,
    format_spec: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Interpolation {
    return { _type: "Interpolation", value, str, conversion, format_spec, lineno, col_offset, end_lineno, end_col_offset };
}

export interface JoinedStr {
    _type: "JoinedStr";
    values: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function JoinedStr(
    values: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): JoinedStr {
    return { _type: "JoinedStr", values, lineno, col_offset, end_lineno, end_col_offset };
}

export interface TemplateStr {
    _type: "TemplateStr";
    values: expr[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function TemplateStr(
    values: expr[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): TemplateStr {
    return { _type: "TemplateStr", values, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Constant {
    _type: "Constant";
    value: ScalarConstant;
    kind: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Constant(
    value: ScalarConstant,
    kind: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Constant {
    return { _type: "Constant", value, kind, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Attribute {
    _type: "Attribute";
    value: expr;
    attr: string;
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Attribute(
    value: expr,
    attr: string,
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Attribute {
    return { _type: "Attribute", value, attr, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Subscript {
    _type: "Subscript";
    value: expr;
    slice: expr;
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Subscript(
    value: expr,
    slice: expr,
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Subscript {
    return { _type: "Subscript", value, slice, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Starred {
    _type: "Starred";
    value: expr;
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Starred(
    value: expr,
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Starred {
    return { _type: "Starred", value, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Name {
    _type: "Name";
    id: string;
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Name(
    id: string,
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Name {
    return { _type: "Name", id, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface List {
    _type: "List";
    elts: expr[];
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function List(
    elts: expr[],
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): List {
    return { _type: "List", elts, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Tuple {
    _type: "Tuple";
    elts: expr[];
    ctx: expr_context;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Tuple(
    elts: expr[],
    ctx: expr_context,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Tuple {
    return { _type: "Tuple", elts, ctx, lineno, col_offset, end_lineno, end_col_offset };
}

export interface Slice {
    _type: "Slice";
    lower: expr | null;
    upper: expr | null;
    step: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function Slice(
    lower: expr | null,
    upper: expr | null,
    step: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): Slice {
    return { _type: "Slice", lower, upper, step, lineno, col_offset, end_lineno, end_col_offset };
}

export type expr_context = Load | Store | Del;
export interface Load {
    _type: "Load";
}
export function Load(
): Load {
    return { _type: "Load" };
}

export interface Store {
    _type: "Store";
}
export function Store(
): Store {
    return { _type: "Store" };
}

export interface Del {
    _type: "Del";
}
export function Del(
): Del {
    return { _type: "Del" };
}

export type boolop = And | Or;
export interface And {
    _type: "And";
}
export function And(
): And {
    return { _type: "And" };
}

export interface Or {
    _type: "Or";
}
export function Or(
): Or {
    return { _type: "Or" };
}

export type operator = Add | Sub | Mult | MatMult | Div | Mod | Pow | LShift | RShift | BitOr | BitXor | BitAnd | FloorDiv;
export interface Add {
    _type: "Add";
}
export function Add(
): Add {
    return { _type: "Add" };
}

export interface Sub {
    _type: "Sub";
}
export function Sub(
): Sub {
    return { _type: "Sub" };
}

export interface Mult {
    _type: "Mult";
}
export function Mult(
): Mult {
    return { _type: "Mult" };
}

export interface MatMult {
    _type: "MatMult";
}
export function MatMult(
): MatMult {
    return { _type: "MatMult" };
}

export interface Div {
    _type: "Div";
}
export function Div(
): Div {
    return { _type: "Div" };
}

export interface Mod {
    _type: "Mod";
}
export function Mod(
): Mod {
    return { _type: "Mod" };
}

export interface Pow {
    _type: "Pow";
}
export function Pow(
): Pow {
    return { _type: "Pow" };
}

export interface LShift {
    _type: "LShift";
}
export function LShift(
): LShift {
    return { _type: "LShift" };
}

export interface RShift {
    _type: "RShift";
}
export function RShift(
): RShift {
    return { _type: "RShift" };
}

export interface BitOr {
    _type: "BitOr";
}
export function BitOr(
): BitOr {
    return { _type: "BitOr" };
}

export interface BitXor {
    _type: "BitXor";
}
export function BitXor(
): BitXor {
    return { _type: "BitXor" };
}

export interface BitAnd {
    _type: "BitAnd";
}
export function BitAnd(
): BitAnd {
    return { _type: "BitAnd" };
}

export interface FloorDiv {
    _type: "FloorDiv";
}
export function FloorDiv(
): FloorDiv {
    return { _type: "FloorDiv" };
}

export type unaryop = Invert | Not | UAdd | USub;
export interface Invert {
    _type: "Invert";
}
export function Invert(
): Invert {
    return { _type: "Invert" };
}

export interface Not {
    _type: "Not";
}
export function Not(
): Not {
    return { _type: "Not" };
}

export interface UAdd {
    _type: "UAdd";
}
export function UAdd(
): UAdd {
    return { _type: "UAdd" };
}

export interface USub {
    _type: "USub";
}
export function USub(
): USub {
    return { _type: "USub" };
}

export type cmpop = Eq | NotEq | Lt | LtE | Gt | GtE | Is | IsNot | In | NotIn;
export interface Eq {
    _type: "Eq";
}
export function Eq(
): Eq {
    return { _type: "Eq" };
}

export interface NotEq {
    _type: "NotEq";
}
export function NotEq(
): NotEq {
    return { _type: "NotEq" };
}

export interface Lt {
    _type: "Lt";
}
export function Lt(
): Lt {
    return { _type: "Lt" };
}

export interface LtE {
    _type: "LtE";
}
export function LtE(
): LtE {
    return { _type: "LtE" };
}

export interface Gt {
    _type: "Gt";
}
export function Gt(
): Gt {
    return { _type: "Gt" };
}

export interface GtE {
    _type: "GtE";
}
export function GtE(
): GtE {
    return { _type: "GtE" };
}

export interface Is {
    _type: "Is";
}
export function Is(
): Is {
    return { _type: "Is" };
}

export interface IsNot {
    _type: "IsNot";
}
export function IsNot(
): IsNot {
    return { _type: "IsNot" };
}

export interface In {
    _type: "In";
}
export function In(
): In {
    return { _type: "In" };
}

export interface NotIn {
    _type: "NotIn";
}
export function NotIn(
): NotIn {
    return { _type: "NotIn" };
}

export interface comprehension {
    _type: "comprehension";
    target: expr;
    iter: expr;
    ifs: expr[];
    is_async: number;
}
export function comprehension(
    target: expr,
    iter: expr,
    ifs: expr[],
    is_async: number,
): comprehension {
    return { _type: "comprehension", target, iter, ifs, is_async };
}

export type excepthandler = ExceptHandler;
export interface ExceptHandler {
    _type: "ExceptHandler";
    type: expr | null;
    name: string | null;
    body: stmt[];
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function ExceptHandler(
    type: expr | null,
    name: string | null,
    body: stmt[],
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): ExceptHandler {
    return { _type: "ExceptHandler", type, name, body, lineno, col_offset, end_lineno, end_col_offset };
}

export interface arguments_ {
    _type: "arguments";
    posonlyargs: arg[];
    args: arg[];
    vararg: arg | null;
    kwonlyargs: arg[];
    kw_defaults: (expr | null)[];
    kwarg: arg | null;
    defaults: expr[];
}
export function arguments_(
    posonlyargs: arg[],
    args: arg[],
    vararg: arg | null,
    kwonlyargs: arg[],
    kw_defaults: (expr | null)[],
    kwarg: arg | null,
    defaults: expr[],
): arguments_ {
    return { _type: "arguments", posonlyargs, args, vararg, kwonlyargs, kw_defaults, kwarg, defaults };
}
export { arguments_ as arguments };

export interface arg {
    _type: "arg";
    arg: string;
    annotation: expr | null;
    type_comment: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function arg(
    arg: string,
    annotation: expr | null,
    type_comment: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): arg {
    return { _type: "arg", arg, annotation, type_comment, lineno, col_offset, end_lineno, end_col_offset };
}

export interface keyword {
    _type: "keyword";
    arg: string | null;
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function keyword(
    arg: string | null,
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): keyword {
    return { _type: "keyword", arg, value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface alias {
    _type: "alias";
    name: string;
    asname: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number | null;
    end_col_offset: number | null;
}
export function alias(
    name: string,
    asname: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number | null,
    end_col_offset: number | null,
): alias {
    return { _type: "alias", name, asname, lineno, col_offset, end_lineno, end_col_offset };
}

export interface withitem {
    _type: "withitem";
    context_expr: expr;
    optional_vars: expr | null;
}
export function withitem(
    context_expr: expr,
    optional_vars: expr | null,
): withitem {
    return { _type: "withitem", context_expr, optional_vars };
}

export interface match_case {
    _type: "match_case";
    pattern: pattern;
    guard: expr | null;
    body: stmt[];
}
export function match_case(
    pattern: pattern,
    guard: expr | null,
    body: stmt[],
): match_case {
    return { _type: "match_case", pattern, guard, body };
}

export type pattern = MatchValue | MatchSingleton | MatchSequence | MatchMapping | MatchClass | MatchStar | MatchAs | MatchOr;
export interface MatchValue {
    _type: "MatchValue";
    value: expr;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchValue(
    value: expr,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchValue {
    return { _type: "MatchValue", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchSingleton {
    _type: "MatchSingleton";
    value: ScalarConstant;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchSingleton(
    value: ScalarConstant,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchSingleton {
    return { _type: "MatchSingleton", value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchSequence {
    _type: "MatchSequence";
    patterns: pattern[];
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchSequence(
    patterns: pattern[],
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchSequence {
    return { _type: "MatchSequence", patterns, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchMapping {
    _type: "MatchMapping";
    keys: expr[];
    patterns: pattern[];
    rest: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchMapping(
    keys: expr[],
    patterns: pattern[],
    rest: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchMapping {
    return { _type: "MatchMapping", keys, patterns, rest, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchClass {
    _type: "MatchClass";
    cls: expr;
    patterns: pattern[];
    kwd_attrs: string[];
    kwd_patterns: pattern[];
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchClass(
    cls: expr,
    patterns: pattern[],
    kwd_attrs: string[],
    kwd_patterns: pattern[],
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchClass {
    return { _type: "MatchClass", cls, patterns, kwd_attrs, kwd_patterns, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchStar {
    _type: "MatchStar";
    name: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchStar(
    name: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchStar {
    return { _type: "MatchStar", name, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchAs {
    _type: "MatchAs";
    pattern: pattern | null;
    name: string | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchAs(
    pattern: pattern | null,
    name: string | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchAs {
    return { _type: "MatchAs", pattern, name, lineno, col_offset, end_lineno, end_col_offset };
}

export interface MatchOr {
    _type: "MatchOr";
    patterns: pattern[];
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function MatchOr(
    patterns: pattern[],
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): MatchOr {
    return { _type: "MatchOr", patterns, lineno, col_offset, end_lineno, end_col_offset };
}

export type type_ignore = TypeIgnore;
export interface TypeIgnore {
    _type: "TypeIgnore";
    lineno: number;
    tag: string;
}
export function TypeIgnore(
    lineno: number,
    tag: string,
): TypeIgnore {
    return { _type: "TypeIgnore", lineno, tag };
}

export type type_param = TypeVar | ParamSpec | TypeVarTuple;
export interface TypeVar {
    _type: "TypeVar";
    name: string;
    bound: expr | null;
    default_value: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function TypeVar(
    name: string,
    bound: expr | null,
    default_value: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): TypeVar {
    return { _type: "TypeVar", name, bound, default_value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface ParamSpec {
    _type: "ParamSpec";
    name: string;
    default_value: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function ParamSpec(
    name: string,
    default_value: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): ParamSpec {
    return { _type: "ParamSpec", name, default_value, lineno, col_offset, end_lineno, end_col_offset };
}

export interface TypeVarTuple {
    _type: "TypeVarTuple";
    name: string;
    default_value: expr | null;
    lineno: number;
    col_offset: number;
    end_lineno: number;
    end_col_offset: number;
}
export function TypeVarTuple(
    name: string,
    default_value: expr | null,
    lineno: number,
    col_offset: number,
    end_lineno: number,
    end_col_offset: number,
): TypeVarTuple {
    return { _type: "TypeVarTuple", name, default_value, lineno, col_offset, end_lineno, end_col_offset };
}

export type AST = mod | stmt | expr | expr_context | boolop | operator | unaryop | cmpop | comprehension | excepthandler | arguments_ | arg | keyword | alias | withitem | match_case | pattern | type_ignore | type_param;
