// Compare a corpus generated by generate_fuzz.py or the parent investigation.
import fs from "node:fs";
import { tokenize } from "./tokenizer.ts";

const path = process.argv[2];
if (!path) throw new Error("Usage: node compare.mjs <corpus.json-or-jsonl>");
const input = fs.readFileSync(path, "utf8");
const corpus = path.endsWith(".jsonl") ? input.trim().split("\n").map(JSON.parse) : JSON.parse(input);
const errorFields = ["name", "message", "lineno", "offset", "end_lineno", "end_offset", "text"];
const failures = [];
let exact = 0;
for (const item of corpus) {
    for (const mode of ["extra", "strict"]) {
        const expected = item[mode];
        let actual;
        try {
            actual = { tokens: tokenize(item.source, { extraTokens: mode === "extra" }) };
        } catch (error) {
            actual = { error: Object.fromEntries(errorFields.map((key) => [key, error[key] ?? null])) };
        }
        if (JSON.stringify(actual.tokens ?? actual.error) === JSON.stringify(expected.tokens ?? expected.error)) {
            exact++;
        } else {
            failures.push({ name: item.name, mode, expected, actual });
        }
    }
}
console.log(JSON.stringify({ cases: corpus.length, modes: corpus.length * 2, exact, failures }, null, 2));
if (failures.length) process.exitCode = 1;
